services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: on-failure
    networks:
      - mynet
  database:
    image: postgres:13.16-bookworm
    ports:
      - "5432:5432"
    networks:
      - mynet
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
networks:
  mynet:
    driver: bridge